### ISSUE TITLE
make fails!

### ISSUE THREAD

**Issue by habibrk** [cezs/jtx1inst#1]
nvidia@tegra-ubuntu:/media/nvidia/2c6c5cb4-7ae8-4363-870e-b924ad98185a/jtx1inst/build$ **sudo i2cdump -y -r 0x14-0x26 2 0x50 b**
[sudo] password for nvidia:
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f    0123456789abcdef
10:             36 39 39 2d 38 32 31 38 30 2d 31 30        **699-82180-10**
20: 30 30 2d 31 30 30 20                               **00-100**

SKU is same as @cezs 's
After doing 'cmake ..', make fails
Please help!

nvidia@tegra-ubuntu:/media/nvidia/2c6c5cb4-7ae8-4363-870e-b924ad98185a/jtx1inst/build$ make
[ 66%] Built target jtx1inst                                                                                              
[ 83%] Linking C executable jtx1inst_demo                                                                                 libjtx1inst.so: undefined reference to `i2c_smbus_read_word_data'                                                         collect2: error: ld returned 1 exit status                                                                                CMakeFiles/jtx1inst_demo.dir/build.make:95: recipe for target 'jtx1inst_demo' failed                                      make[2]: *** [jtx1inst_demo] Error 1                                                                                      CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/jtx1inst_demo.dir/all' failed                                     make[1]: *** [CMakeFiles/jtx1inst_demo.dir/all] Error 2                                                                   Makefile:127: recipe for target 'all' failed                                                                              
make: *** [all] Error 2

**Comment by cezs** [comment]
Perhaps installing userspace I2C programming library development files with `sudo apt-get install libi2c-dev` should help you?

**Comment by habibrk** [comment]
@cezs thanks for the prompt reply... it worked !
 
however, one should do following while in /path/to/build
$ rm -rf *                  # to clear the build
$ cmake ..
$ make

and it should work ....

**Comment by cezs** [comment]
Ok. Thank you for the heads up, I will mark this issue as solved then.
