### ISSUE TITLE
Measurement problem ?

### ISSUE THREAD

**Issue by nicolasGab** [cezs/jtx1inst#7]
How can you get the following power value with the associated voltage and current?
[POWER] module power input: 3898.000mW

[CURRENT] module power input: 3860.000mA

[VOLTAGE] module power input: 3438.000mV

Since P = U x I, power should be 3.86 x 3.438 = 13,3 W

You also write:
[VOLTAGE] main carrier board 5V supply: 19112.000mV
[VOLTAGE] main carrier board 3.3V supply: 4976.000mV

Does that mean 5V = 19V or that there is overvoltage?

Does this have anything to do with the module version? From the Nvidia forums:

> The feature to enable use of INA monitors was added starting with revision 300 of Jetson TX1. For example, SKU 699-82180-1000-300 (note the "-300") has the feature.

**Comment by cezs** [comment]
Seems like the the next two are wrongly reported as current and voltage, while in fact both of these are powers output in watts. See 91455d03ac198e80f8fe6ad5eff8f0deff7209f6, 2d7bc537d6ffd024cf18c2baef4d98cdd068e3ab, e0fa28a333bacdcf70098824d110f6569ab71469 and f2def1b0b63fc34fbff2fc93945a972ba907a691 for fixes. 
Reading through sysf might not always work, although in regards to second question, it is in fact 19 V with wrong description. I'm going to move the sample application to other repository.
